### ISSUE TITLE
profile_side_switcher.css is not within the allowed path(s)

### ISSUE THREAD

**Issue by LtbBer** [Tatiana5/profile_side_switcher#11]
Hi, many thanks for this great extension....it works great, much better than the other ones I found. However, I face an issue in my phpbb 3.1.4 installation. When I send some PM, the error message appears just above the web page saying this:
Warning: file_exists() [function.file-exists]: open_basedir restriction in effect. File(./../../prosilver/theme/en/profile_side_switcher.css) is not within the allowed path(s)...

Any idea why it is happening and how to solve it?
thnks

**Comment by lavigor** [comment]
Hi, @LtbBer.
Does the problem still persists?
Do you have it anywhere else?

**Comment by lavigor** [comment]
If you have a problem, you can open a new issue and describe it.
This issue is considered closed.

**Comment by LtbBer** [comment]
Hi,
thanks for asking. At the end I found the way how to get rid of this message...had the
issue also with some other extensions (2 more).

It was just about the path to theme file, if you are interested (maybe someone else could
have the same problem), please see more details here:
https://www.phpbb.com/customise/db/extension/boardrules/support/topic/132686?p=441006#p441006

Thanks
Ltb

**Comment by Galixte** [comment]
Hi @LtbBer,

what is the other extensions ? Board rules and… ?

**Comment by lavigor** [comment]
@Galixte, [this commit](https://github.com/Tatiana5/profile_side_switcher/commit/8ec51ea43249e885f8a95c72b3d776822cdab376) fixes the issue.

**Comment by LtbBer** [comment]
Hi @Galixte,
the other extension in which I faced the issue is "on_and_offlinestatus_extension" (https://www.phpbb.de/community/viewtopic.php?f=149&t=233755). Probably not an official one, but have the same incompatibility with open_basedir (I did not inform.the author yet, installed it just yesterday).

Thanks for your help.
