### ISSUE TITLE
Compatibility with Newspage extension

### ISSUE THREAD

**Issue by Galixte** [Tatiana5/profile_side_switcher#20]
Hi @lavigor,

since your last commit, here: https://github.com/Tatiana5/profile_side_switcher/commit/9fd449e54d409f9b26257e4f68d9b60cb18c4d73, the Newspage extension has an issue when the user chooses the displaying of mini-profile on left and chooses do not show the mini-profil on the News pages (with Newspage extension) : a column empty is displayed on left.

Newspage extension is available here: https://github.com/nickv-phpbb/phpbb-ext-newspage.

**Comment by lavigor** [comment]
Hi, @Galixte.

That extension is not coded properly.
```
[phpBB Debug] PHP Notice: in file [ROOT]/ext/nickvergessen/newspage/newspage.php on line 352: Undefined index: EDITED_TIMES_TOTAL
```

However, I've made the fix. =)

**Comment by Galixte** [comment]
Thanks !
