### ISSUE TITLE
Compatibility with phpbb 3.3.0 ?

### ISSUE THREAD

**Issue by panteror** [Tatiana5/profile_side_switcher#28]
Hi,

You extension seems incompatible with new phpbb 3.3.0 release.
Can you fix it ?
Here the logs on my test website 

> Fatal error: Uncaught Twig\Error\LoaderError: Looks like you try to load a template outside configured directories (@tatiana5_profilesideswitcher/../../flat-style-blue/theme/fr/profile_side_switcher.css) in "@tatiana5_profilesideswitcher/event/overall_header_head_append.html" at line 2. in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\dowtest\forum\vendor\twig\twig\src\Loader\FilesystemLoader.php:291 Stack trace: #0 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\dowtest\forum\vendor\twig\twig\src\Loader\FilesystemLoader.php(209): Twig\Loader\FilesystemLoader->validateName('@tatiana5_profi...') #1 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\dowtest\forum\phpbb\template\twig\loader.php(135): Twig\Loader\FilesystemLoader->findTemplate('@tatiana5_profi...', true) #2 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\dowtest\forum\vendor\twig\twig\src\Loader\FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate('@tatiana5_profi...') #3 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-ww in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\dowtest\forum\vendor\twig\twig\src\Loader\FilesystemLoader.php on line 291

Thanks for your work.

**Comment by iasdeoupxe** [comment]
Could be already fixed by b57a53dc8959630eae84811cc64c3281f1a3175a

**Comment by Feuer-sturm** [comment]
I just updated to phpbb 3.3.9 and downloaded the zip of the plugin today with the last commit from "Commits on Nov 29, 2022" and I had no problems with the extenion.
