### ISSUE TITLE
Compatibility with 3.3.1

### ISSUE THREAD

**Issue by bug-i** [Tatiana5/profile_side_switcher#29]
This extension doesnt work properly with the new phpbb 3.3.1
In some resolutions there are shifted frames, see screenshot attached.

![Screenshot_20200808-163013](https://user-images.githubusercontent.com/29623218/89713012-f65e8c00-d994-11ea-806e-fe1ded3cf4b2.jpg)

**Comment by Tatiana5** [comment]
Fixed

**Comment by bug-i** [comment]
@Tatiana5 Wouldnt it make sense to release a new version 1.0.2 that includes all the changes instead of just having the master branch up to date?

**Comment by Tatiana5** [comment]
@bug-i I don't have enough time for this
It took more than a year to make ready-made changes to the branch
