### ISSUE TITLE
Broken layout when displaying posts of ignored users 

### ISSUE THREAD

**Issue by shredEngineer** [Tatiana5/profile_side_switcher#31]
Hey,

I'm using your plugin with phpBB 3.3.5. It works great for normal posts.

But when displaying posts of ignored users, the layout is broken:

![Bildschirmfoto von 2022-01-23 13-20-24](https://user-images.githubusercontent.com/39415391/150678195-36e08dca-6e4f-4f4d-a18d-e580c0bea179.png)

**Comment by Tatiana5** [comment]
Fixed
